### ISSUE TITLE
Break long title in new line

### ISSUE THREAD

**Issue by midzer** [lokal-ninja/ln-base#11]
Long titles don't break properly.
Check out https://lokal.ninja/oesterreich/wien/fahrrad-selbsthilfe-werkstatt-im-wuk/ on mobile.

Maybe there is some kind of CSS property to fix this.

**Comment by 4Rebin** [comment]
Hey,  I would like to work on this issue.

**Comment by UmarGit** [comment]
**Hey @midzer I have Solved your Issue**

**Comment by Trustidiong** [comment]
Hey, I would like to work on this. I think it will be fun

**Comment by midzer** [comment]
Hi @4Rebin @UmarGit @Trustidiong 
once Hacktoberfest starts in 7 days, i would be happy to welcome a PR from you :)

**Comment by 4Rebin** [comment]
I have mistake I sent the PR before the hacktoberfest could you please fixe that. thanks.
