### ISSUE TITLE
Mention how to add entries on city details page

### ISSUE THREAD

**Issue by moba** [lokal-ninja/ln-base#29]
On the front page, you mention Openstreetmap and that missing entries should be added there. I think it would be a good idea to also do that on the individual city listings, near the end of the page, e.g. "Missing an entry? Please add it to the free database at OpenStreetMap!", "Help improve the public data set by adding missing entries at OpenStreetMap" or something along those lines.

**Comment by midzer** [comment]
Done by https://github.com/lokal-ninja/ln-base/commit/4065a56f62dd48dba3d37cbb5bedc8bef8c3805e
