### ISSUE TITLE
Set correct background color for wttr widget

### ISSUE THREAD

**Issue by midzer** [lokal-ninja/ln-base#36]
We can now set a proper wttr widget background color matching our theme color:

Example: https://wttr.in/Munich_I_background=FFFFFF.png

**Comment by sirish123** [comment]
I have downloaded the code and tried to open using vs code, can you please elaborate on what the issue is?

**Comment by midzer** [comment]
@sirish123 Have a look at https://github.com/lokal-ninja/ln-base/blob/master/README.md on how to setup a region project with this theme.

The wttr widget in question is located here https://github.com/lokal-ninja/ln-base/blob/032552a5102811191e635e284c2635d0d095bea4/layouts/_default/single.html#L42 for example. On section page, too

**Comment by midzer** [comment]
This adaption has to be done via JS after load, because we cannot determine dark/light theme of user on build time.

Default should be light background as most users are likely to not have dark theme enabled system wide.

**Comment by midzer** [comment]
done via https://github.com/lokal-ninja/ln-base/commit/3523fcee1ee54670f70cac26f3ea9de77bf724c9
