### ISSUE TITLE
Link to Google Maps

### ISSUE THREAD

**Issue by midzer** [lokal-ninja/ln-base#7]
Introduce a new button next to the OSM one in not loaded map.

Use (always existing) adress and generate link following https://www.google.com/maps/dir//Aumühle+2,+82275+Emmering/ scheme.

**Comment by ReyhanSara** [comment]
Hi, Can I work on this?

**Comment by midzer** [comment]
@ReyhanSara Of course, you can work on this one in parallel. But maybe finish https://github.com/lokal-ninja/ln-base/pull/18 first?

**Comment by ReyhanSara** [comment]
Could you please specify the file that requires to be modified?
