### ISSUE TITLE
Telephone Links

### ISSUE THREAD

**Issue by midzer** [lokal-ninja/ln-base#8]
Link telephone number in info block like `<a href="tel:+01-562-867-5309">1-562-867-5309</a>`

and style it
```
a[href^="tel:"]:before {
  content: "\260e";
  margin-right: 0.5em;
}
```
Don't forget to add the extra hypens in the link.

Reference: https://css-tricks.com/the-current-state-of-telephone-links/

**Comment by ReyhanSara** [comment]
Could you please tell me which file contains the telephone number block?

**Comment by midzer** [comment]
Hi @ReyhanSara 
Great that you want to have a look! :+1: 

In case you want to participate in https://hacktoberfest.digitalocean.com/, you can wait 9 more days for PR.

Here's the relevant line https://github.com/lokal-ninja/ln-base/blob/f2e75a16a79a091e3483841e4839bbf4c8ddd472/layouts/_default/single.html#L18

**Comment by ReyhanSara** [comment]
Yes, I'm looking forward to participate and this is my first time.
Will have a look at it. Thank you!

**Comment by ReyhanSara** [comment]
Hi. I'm trying to view the output of the file on Chrome and all I see is the source code. Appreciate if you can guide me on this.

**Comment by midzer** [comment]
@ReyhanSara Sorry, this repository is lacking a proper `README.md`. I will write one the next days.

Basically, this is a https://gohugo.io/ theme. It is included as a submodule for one of the other `data` repositories in this organisation. Let's see how far you can go with this info or wait until I've written a Setup guide.

**Comment by ReyhanSara** [comment]
oh okay. Now that I have this information I shall do a research on it and see what I can do till then.

**Comment by ReyhanSara** [comment]
Hi there. I just fixed the telephone link issue. I hope it's correct.

**Comment by midzer** [comment]
Closing now as I've merged https://github.com/lokal-ninja/ln-base/pull/18
